### ISSUE TITLE
Use with AWS Mock ec2metadata service?

### ISSUE THREAD

**Issue by StevenACoffman** [mumoshu/kube-magic-ip-address#1]
Is it possible to use this repository in minikube to redirect traffic whose destination is 169.254.169.254 (AWS/GCP Metadata service endpoint) to another container([aws-mock-metadata](https://github.com/jtblin/aws-mock-metadata))?

I see that [you have presented](https://www.slideshare.net/mumoshu/from-dev-to-prod-kubernetes-on-aws-short-ver) on using [docker-iptables-redirector](https://github.com/fabric8io/docker-iptables-redirector/pull/1) on the host, and I was looking to see if you had a chart or example when I found this repository. Any pointers would be very much appreciated!

**Comment by mumoshu** [comment]
Hi! Yep in theory it should just work.

Could you deploy aws-mock-metadata as a daemonset? Suppose you have pod labels like `app=aws-mock-metadata`, set it to the SELECTOR envvar of the magic-ip-assigner daemonset, and `169.254.169.254` to the MAGIC_IP envvar.

https://github.com/mumoshu/kube-magic-ip-address/blob/dc30f61e50abf8bed5db447225b1906ea2613f3c/magic-ip-assigner.daemonset.yaml#L29

**Comment by StevenACoffman** [comment]
I wonder if the HOST_INTERFACE for minikube should be docker0 or eth0 instead of cni0?

It doesn't appear to be working for me. I set up my minikube like this:
```
minikube start --extra-config=apiserver.authorization-mode=RBAC
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
kubectl create clusterrolebinding default-cluster-admin --clusterrole=cluster-admin --serviceaccount=default:default
kubectl -n kube-system create sa tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

# Set up AWS credentials as secrets
kubectl create secret generic aws-creds --from-literal=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --from-literal=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
```
I have then applied the [jtblin/aws-mock-metadata](https://github.com/jtblin/aws-mock-metadata) with this daemonset.yaml manifest:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aws-mock
  labels:
    app: aws-mock
spec:
  selector:
    matchLabels:
      app: aws-mock
  template:
    metadata:
      name: aws-mock
      labels:
        app: aws-mock
    spec:
      containers:
      - image: jtblin/aws-mock-metadata
        imagePullPolicy: Always
        name: aws-mock
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        args:
          - "--availability-zone=us-east-1d"
          - "--instance-id=i-0a148cec064fc841c"
          - "--app-port=80"
          - "--private-ip=172.28.159.34"
```
This works as an ec2 metadata, which I can verify by running a nodePort service that exposes it, but when I run kube-magic-ip like so:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: magic-ip-assigner
  labels:
    app: magic-ip-assigner
spec:
  selector:
    matchLabels:
       app: magic-ip-assigner
  template:
    metadata:
      name: magic-ip-assigner
      labels:
        app: magic-ip-assigner
    spec:
      hostNetwork: true
      containers:
        - name: magic-ip-assigner
          image: mumoshu/kube-magic-ip-assigner:0.9.0-1.9.8
          securityContext:
            privileged: true
            capabilities:
              add: [NET_ADMIN]
          env:
          - name: PORT
            value: "80"
          - name: TARGET
            value: "80"
          - name: SELECTOR
            value: "run=aws-mock"
          - name: PROTOCOL
            value: tcp
          - name: MAGIC_IP
            value: 169.254.169.254
          - name: HOST_INTERFACE
            value: cni0
          - name: VERBOSE
            value: "1"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

```
Curl commands from pods inside the cluster still do not connect on that IP address.
Do you have any insight you can share? I think there is a lot of potential, but I feel like I'm making a dumb mistake.
